export const ACTION_PLAYER_SET_HIT_DICE_COUNT = Symbol('ACTION_PLAYER_SET_HIT_DICE_COUNT')
export const ACTION_PLAYER_SET_HIT_DICE_SIDES = Symbol('ACTION_PLAYER_SET_HIT_DICE_SIDES')
export const ACTION_PLAYER_SET_HIT_DICE_MOD = Symbol('ACTION_PLAYER_SET_HIT_DICE_MOD')

export const ACTION_PLAYER_SET_DAMAGE_DICE_COUNT = Symbol('ACTION_PLAYER_SET_DAMAGE_DICE_COUNT')
export const ACTION_PLAYER_SET_DAMAGE_DICE_SIDES = Symbol('ACTION_PLAYER_SET_DAMAGE_DICE_SIDES')
export const ACTION_PLAYER_SET_DAMAGE_DICE_MOD = Symbol('ACTION_PLAYER_SET_DAMAGE_DICE_MOD')
